In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from datetime import datetime
import polars as pl
import duckdb
import glob
import duckdb
import gc
import os

C:\Users\diego\anaconda3\Lib\site-packages\polars\meta\build.py:5: UserWarning: Polars binary is missing!
  from polars._utils.polars_version import get_polars_version

#### Carregando os dataset

In [3]:
df_atlas = pd.read_csv('raw/mundo_onu_adh_municipio (1).csv')

In [4]:
df_hepa = pd.read_parquet('../model_v1_explicabilidade/processed/df_hepat_processed_v1.parquet')

#### Select columns Atlas

In [6]:
columns_atlas = ["id_municipio","expectativa_vida","fecundidade_total","prob_sobrevivencia_40","prob_sobrevivencia_60","taxa_freq_bruta_basico","taxa_freq_bruta_fundamental","taxa_freq_bruta_medio","taxa_freq_liquida_superior","prop_pobreza_extrema","prop_vulner_pobreza","taxa_agua_encanada","taxa_banheiro_agua_encanada","taxa_coleta_lixo","taxa_energia_eletrica","taxa_agua_esgoto_inadequados","taxa_paredes_inadequados","populacao","indice_escolaridade","indice_frequencia_escolar","idhm","idhm_e","idhm_l","idhm_r"]

In [7]:
df_atlas=df_atlas[columns_atlas]

### Select columns Hepa

In [9]:
cols_drop=[
'DT_NOTIFIC','ANO_MES','NU_ANO',# Datas suporte
'TP_NOT', 'ID_AGRAVO','ID_REGIONA', 'ID_RG_RESI', #identificação 
'SEM_NOT', # feature de calendario
'DT_INVEST','DT_ENCERRA', 'ano',  # oq é investigaão
'DT_DIAG', 'SEM_DIAG', # diagnostico 
'SEXUAL','DOMICILI', 'OCUPACIO', 'MEDICAMENT', 'TATU_PIER', 'MATBIOLOGI','INAL_CRACK', 'ACUPUNTURA', 'TRANSFUSAO', 'INJETAVEIS','CIRURGICO', 'AGUA_ALIME', 'DENTARIO', 'TRESMAIS', 'HEMODIALIS',# contemplado nas variaveis construidas
'HEPATITE_N', 'HEPATITA', 'HEPATITB', 'INSTITUCIO', 'HIV', 'OUTRA_DST','HAV','HBV','HCV','HDV','HEV','GEN_VHC','ANTIHAVIGM', 'ANTIHBS','ANTIHDVIGM', 'AGHBS', 'AGHBE', 'ANTIHEVIGM', 'ANTIHBCIGM', 'ANTIHBE','ANTIHCV', 'HBC_TOTAL', 'ANTIHDV', 'TP_SOROHCV', # contemplado nas variaveis construidas
'CO_UF_EXP', 'CO_MUN_EXP','CO_UF_EX2', 'CO_MUN_EX2', 'CO_UF_EX3', 'CO_MUN_EX3', # provavel localidade da infeccção (hipoteses)  
'DT_ACIDENT', # datas criptografadas
'DT_COLETA','RES_HBSAG', 'RE_ANTIHBC', 'RE_ANTIHCV', # muitos valores faltantes nesses resultados
'TRANSPLA', 'OUTRAS', # contemplado nas variaveis construidas
'FORMA', # relacionada com a resposta
'DSFONTE'] # campo texto
df_train=df_hepa.loc[:, ~df_hepa.columns.isin(cols_drop)]

In [10]:
df_train.columns = [col.lower() for col in df_train.columns ]
df_train['id_municip']=df_train.id_municip.astype(int)
df_train.rename({'id_municip':'id_municipio'},axis=1,inplace=True)

C:\Users\diego\AppData\Local\Temp\ipykernel_41180\3820349990.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train['id_municip']=df_train.id_municip.astype(int)
C:\Users\diego\AppData\Local\Temp\ipykernel_41180\3820349990.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train.rename({'id_municip':'id_municipio'},axis=1,inplace=True)

In [11]:
df_train

,sg_uf_not,id_municipio,nu_idade_n,cs_sexo,cs_gestant,cs_raca,cs_escol_n,sg_uf,id_mn_resi,id_pais,...,trimestre,is_fim_semana,is_inicio_ano,is_meio_ano,is_final_ano,mes_sen,mes_cos,dia_sen,dia_cos,is_feriado
0,52,520870,4044,M,06,1,06,52,522045,1,...,1,False,True,False,False,5.000000e-01,0.866025,2.012985e-01,0.97953,False
1,17,170210,4020,F,02,4,05,17,170210,1,...,1,False,True,False,False,5.000000e-01,0.866025,2.012985e-01,0.97953,False
2,33,330455,4023,M,06,4,09,33,330455,1,...,1,False,True,False,False,5.000000e-01,0.866025,2.012985e-01,0.97953,False
3,16,160030,4032,F,99,2,08,16,160030,1,...,1,False,True,False,False,5.000000e-01,0.866025,2.012985e-01,0.97953,False
4,12,120040,4055,M,06,4,00,12,120043,1,...,1,False,True,False,False,5.000000e-01,0.866025,2.012985e-01,0.97953,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33201,31,314310,4031,F,02,4,06,31,314310,1,...,4,True,False,False,True,-2.449294e-16,1.000000,-2.012985e-01,0.97953,False
33202,13,130140,4092,M,06,1,01,13,130140,1,...,4,True,False,False,True,-2.449294e-16,1.000000,-2.012985e-01,0.97953,False
33203,15,150034,4030,M,06,2,09,15,150034,1,...,4,True,False,False,True,-2.449294e-16,1.000000,-2.449294e-16,1.00000,False
33204,13,130100,4047,M,06,4,03,13,130100,1,...,4,True,False,False,True,-2.449294e-16,1.000000,-2.449294e-16,1.00000,False
33205,41,410480,4019,F,01,1,03,41,412090,1,...,4,True,False,False,True,-2.449294e-16,1.000000,-2.449294e-16,1.00000,False

In [12]:
df_atlas['id_municipio'] = df_atlas['id_municipio']//10
df_atlas_recent=df_atlas.groupby('id_municipio').tail(1)

In [13]:
df_merge=pd.merge(df_train,df_atlas_recent,on=['id_municipio'],how='inner')

### Merge dados Ocupação Ministério do Trabalho

In [15]:
# Baixe ou clone o repositório datasets-br/cbo e carregue o arquivo
url = "https://raw.githubusercontent.com/datasets-br/cbo/master/data/lista.csv"
cbo = pd.read_csv(url, dtype={"codigo": str})
cbo['codigo'] = cbo['codigo'].apply(lambda x: x.replace('-',''))
#cbo['codigo'] = pd.to_numeric(cbo['codigo'],errors='coerce') 
# Criar dicionário código → termo
mapa_cbo = dict(zip(cbo["codigo"], cbo["termo"]))

def mapear_ocupacao(df, coluna="id_ocupa_n"):
    df = df.copy()
    df[coluna] = df[coluna].map(mapa_cbo)
    df[coluna] =df[coluna].fillna('Nao informado')
    return df

In [16]:
df_merge=mapear_ocupacao(df_merge, coluna="id_ocupa_n")

In [17]:
df_merge

,sg_uf_not,id_municipio,nu_idade_n,cs_sexo,cs_gestant,cs_raca,cs_escol_n,sg_uf,id_mn_resi,id_pais,...,taxa_energia_eletrica,taxa_agua_esgoto_inadequados,taxa_paredes_inadequados,populacao,indice_escolaridade,indice_frequencia_escolar,idhm,idhm_e,idhm_l,idhm_r
0,52,520870,4044,M,06,1,06,52,522045,1,...,99.96,1.56,0.16,1302001,0.714,0.752,0.799,0.739,0.838,0.824
1,17,170210,4020,F,02,4,05,17,170210,1,...,98.97,4.45,3.13,150484,0.639,0.751,0.752,0.712,0.821,0.727
2,33,330455,4023,M,06,4,09,33,330455,1,...,99.97,0.30,0.52,6320446,0.722,0.717,0.799,0.719,0.845,0.840
3,16,160030,4032,F,99,2,08,16,160030,1,...,99.81,16.25,3.38,398204,0.679,0.655,0.733,0.663,0.820,0.723
4,12,120040,4055,M,06,4,00,12,120043,1,...,99.34,18.43,5.52,336038,0.607,0.690,0.727,0.661,0.798,0.729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323671,31,314310,4031,F,02,4,06,31,314310,1,...,99.83,0.41,0.07,45772,0.443,0.733,0.728,0.620,0.868,0.716
323672,13,130140,4092,M,06,1,01,13,130140,1,...,82.73,37.26,13.42,30665,0.323,0.498,0.563,0.431,0.756,0.548
323673,15,150034,4030,M,06,2,09,15,150034,1,...,94.23,19.47,11.74,25057,0.250,0.505,0.564,0.399,0.797,0.563
323674,13,130100,4047,M,06,4,03,13,130100,1,...,92.57,38.15,2.94,25774,0.339,0.460,0.549,0.416,0.745,0.534
323675,41,410480,4019,F,01,1,03,41,412090,1,...,99.75,0.59,1.14,286205,0.630,0.783,0.782,0.728,0.846,0.776

Save file

In [19]:
df_merge.to_parquet('processed/df_hepa_atlas.parquet')

In [36]:
df_merge.to_csv('processed/df_hepa_atlas.csv',index=False)

In [38]:
cbo.to_csv('raw/lista_cbo.csv')