In [5]:
!pip install polars duckdb

Requirement already satisfied: polars in c:\users\diego\appdata\local\programs\python\python310\lib\site-packages (1.35.2)
Collecting duckdb
  Downloading duckdb-1.4.2-cp310-cp310-win_amd64.whl.metadata (4.3 kB)
Requirement already satisfied: polars-runtime-32==1.35.2 in c:\users\diego\appdata\local\programs\python\python310\lib\site-packages (from polars) (1.35.2)
Downloading duckdb-1.4.2-cp310-cp310-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 479.2 kB/s eta 0:00:25
   - -------------------------------------- 0.5/12.3 MB 479.2 kB/s eta 0:00:25
   -- ------------------------------------- 0.8/12.3 MB 516.0 kB/s eta 0:00:23
   -- ------------------------------------- 0.8/12.3 MB 516.0 kB/s eta 0:00:23
   --- ------------------------------------ 1.0/12.3 MB 524.3 kB/s eta 0:00:22
   --- ------------------------------------ 1.0/12.3 MB 524.3 kB/s eta 0:00:22
   ---- ----------------------------------- 1.3/12.3 MB 536.9 kB/s eta 0:00:21
   ---- ----------------------------------- 1.3/12.3 MB 536.9 kB/s eta 0:00:21
   ---- ----------------------------------- 1.3/12.3 MB 536.9 kB/s eta 0:00:21
   ----- ---------------------------------- 1.6/12.3 MB 524.3 kB/s eta 0:00:21
   ----- ---------------------------------- 1.8/12.3 MB 553.0 kB/s eta 0:00:19
   ----- ---------------------------------- 1.8/12.3 MB 553.0 kB/s eta 0:00:19
   ----- ---------------------------------- 1.8/12.3 MB 553.0 kB/s eta 0:00:19
   ------ --------------------------------- 2.1/12.3 MB 531.4 kB/s eta 0:00:20
   ------ --------------------------------- 2.1/12.3 MB 531.4 kB/s eta 0:00:20
   ------- -------------------------------- 2.4/12.3 MB 536.9 kB/s eta 0:00:19
   ------- -------------------------------- 2.4/12.3 MB 536.9 kB/s eta 0:00:19
   -------- ------------------------------- 2.6/12.3 MB 545.1 kB/s eta 0:00:18
   -------- ------------------------------- 2.6/12.3 MB 545.1 kB/s eta 0:00:18
   -------- ------------------------------- 2.6/12.3 MB 545.1 kB/s eta 0:00:18
   --------- ------------------------------ 2.9/12.3 MB 532.6 kB/s eta 0:00:18
   --------- ------------------------------ 2.9/12.3 MB 532.6 kB/s eta 0:00:18
   --------- ------------------------------ 2.9/12.3 MB 532.6 kB/s eta 0:00:18
   --------- ------------------------------ 2.9/12.3 MB 532.6 kB/s eta 0:00:18
   ---------- ----------------------------- 3.1/12.3 MB 500.1 kB/s eta 0:00:19
   ---------- ----------------------------- 3.1/12.3 MB 500.1 kB/s eta 0:00:19
   ---------- ----------------------------- 3.1/12.3 MB 500.1 kB/s eta 0:00:19
   ---------- ----------------------------- 3.1/12.3 MB 500.1 kB/s eta 0:00:19
   ---------- ----------------------------- 3.1/12.3 MB 500.1 kB/s eta 0:00:19
   ----------- ---------------------------- 3.4/12.3 MB 455.5 kB/s eta 0:00:20
   ----------- ---------------------------- 3.4/12.3 MB 455.5 kB/s eta 0:00:20
   ----------- ---------------------------- 3.4/12.3 MB 455.5 kB/s eta 0:00:20
   ----------- ---------------------------- 3.4/12.3 MB 455.5 kB/s eta 0:00:20
   ----------- ---------------------------- 3.4/12.3 MB 455.5 kB/s eta 0:00:20
   ----------- ---------------------------- 3.7/12.3 MB 426.8 kB/s eta 0:00:21
   ----------- ---------------------------- 3.7/12.3 MB 426.8 kB/s eta 0:00:21
   ------------ --------------------------- 3.9/12.3 MB 441.5 kB/s eta 0:00:19
   ------------- -------------------------- 4.2/12.3 MB 450.2 kB/s eta 0:00:19
   ------------- -------------------------- 4.2/12.3 MB 450.2 kB/s eta 0:00:19
   -------------- ------------------------- 4.5/12.3 MB 460.5 kB/s eta 0:00:18
   -------------- ------------------------- 4.5/12.3 MB 460.5 kB/s eta 0:00:18
   --------------- ------------------------ 4.7/12.3 MB 468.3 kB/s eta 0:00:17
   --------------- ------------------------ 4.7/12.3 MB 468.3 kB/s eta 0:00:17
   ---------------- ----------------------- 5.0/12.3 MB 474.9 kB/s eta 0:00:16
   ---------------- ----------------------- 5.0/12.3 MB 474.9 kB/s eta 0:00:16
   ---------------- ----------------------- 5.0/12.3 MB 474.9 kB/s eta 0:00:16
   ----------------- ---------------------- 5.2/12.3 MB 473.6 kB/s eta 0:00:15
   ----------------- ---------------------- 5.2/12.3 MB 473.6 kB/s eta 0:00:15
   ----------------- ---------------------- 5.5/12.3 MB 477.3 kB/s eta 0:00:15
   ----------------- ---------------------- 5.5/12.3 MB 477.3 kB/s eta 0:00:15
   ----------------- ---------------------- 5.5/12.3 MB 477.3 kB/s eta 0:00:15
   ------------------ --------------------- 5.8/12.3 MB 475.5 kB/s eta 0:00:14
   ------------------ --------------------- 5.8/12.3 MB 475.5 kB/s eta 0:00:14
   ------------------- -------------------- 6.0/12.3 MB 478.1 kB/s eta 0:00:14
   ------------------- -------------------- 6.0/12.3 MB 478.1 kB/s eta 0:00:14
   ------------------- -------------------- 6.0/12.3 MB 478.1 kB/s eta 0:00:14
   -------------------- ------------------- 6.3/12.3 MB 475.2 kB/s eta 0:00:13
   -------------------- ------------------- 6.3/12.3 MB 475.2 kB/s eta 0:00:13
   --------------------- ------------------ 6.6/12.3 MB 475.9 kB/s eta 0:00:13
   --------------------- ------------------ 6.6/12.3 MB 475.9 kB/s eta 0:00:13
   ---------------------- ----------------- 6.8/12.3 MB 479.9 kB/s eta 0:00:12
   ---------------------- ----------------- 6.8/12.3 MB 479.9 kB/s eta 0:00:12
   ---------------------- ----------------- 7.1/12.3 MB 488.5 kB/s eta 0:00:11
   ----------------------- ---------------- 7.3/12.3 MB 496.1 kB/s eta 0:00:11
   ----------------------- ---------------- 7.3/12.3 MB 496.1 kB/s eta 0:00:11
   ----------------------- ---------------- 7.3/12.3 MB 496.1 kB/s eta 0:00:11
   ------------------------ --------------- 7.6/12.3 MB 493.4 kB/s eta 0:00:10
   ------------------------ --------------- 7.6/12.3 MB 493.4 kB/s eta 0:00:10
   ------------------------- -------------- 7.9/12.3 MB 498.0 kB/s eta 0:00:09
   -------------------------- ------------- 8.1/12.3 MB 507.4 kB/s eta 0:00:09
   --------------------------- ------------ 8.4/12.3 MB 516.5 kB/s eta 0:00:08
   ---------------------------- ----------- 8.7/12.3 MB 527.4 kB/s eta 0:00:07
   ---------------------------- ----------- 8.9/12.3 MB 535.9 kB/s eta 0:00:07
   ----------------------------- ---------- 9.2/12.3 MB 546.4 kB/s eta 0:00:06
   ------------------------------ --------- 9.4/12.3 MB 557.7 kB/s eta 0:00:06
   -------------------------------- ------- 10.0/12.3 MB 575.3 kB/s eta 0:00:05
   --------------------------------- ------ 10.2/12.3 MB 583.8 kB/s eta 0:00:04
   ---------------------------------- ----- 10.7/12.3 MB 606.8 kB/s eta 0:00:03
   ----------------------------------- ---- 11.0/12.3 MB 617.5 kB/s eta 0:00:03
   ------------------------------------- -- 11.5/12.3 MB 638.4 kB/s eta 0:00:02
   ---------------------------------------  12.1/12.3 MB 662.3 kB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 671.7 kB/s  0:00:18
Installing collected packages: duckdb
Successfully installed duckdb-1.4.2

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from datetime import datetime
import polars as pl
import duckdb
import glob
import duckdb
import gc
import os

pd.set_option('display.max_columns',999)

#### Carregando os dataset

In [7]:
df_atlas = pd.read_csv('raw/mundo_onu_adh_municipio (1).csv')

In [8]:
df_lept = pd.read_parquet('processed/df_hepat_processed_v1.parquet')

#### Select columns Atlas

In [9]:
columns_atlas = ["id_municipio","expectativa_vida","fecundidade_total","prob_sobrevivencia_40","prob_sobrevivencia_60","taxa_freq_bruta_basico","taxa_freq_bruta_fundamental","taxa_freq_bruta_medio","taxa_freq_liquida_superior","prop_pobreza_extrema","prop_vulner_pobreza","taxa_agua_encanada","taxa_banheiro_agua_encanada","taxa_coleta_lixo","taxa_energia_eletrica","taxa_agua_esgoto_inadequados","taxa_paredes_inadequados","populacao","indice_escolaridade","indice_frequencia_escolar","idhm","idhm_e","idhm_l","idhm_r"]

In [10]:
df_atlas=df_atlas[columns_atlas]

### Make df_train

In [12]:
df_train=df_lept.copy()

In [13]:
df_train.columns = [col.lower() for col in df_train.columns ]
df_train['id_municip']=df_train.id_municip.astype(int)
df_train.rename({'id_municip':'id_municipio'},axis=1,inplace=True)

In [14]:
df_train

,tp_not,id_agravo,dt_notific,sem_not,nu_ano,sg_uf_not,id_municipio,id_regiona,id_unidade,dt_sin_pri,...,baixa_escolaridade,raca_vulneravel,faixa_vulneravel,vulnerabilidade_social,nivel_vulnerabilidade,alta_vulnerabilidade,mes_sintomas,semana_sintomas,estacao,periodo_chuvoso
0,Surto,Leptospirose nao especificada,1420070400000000000,201453,2015,Minas Gerais (MG),317020,1462,5617286,2014-12-28,...,0,0,1,1,Moderada,0,12,52,Verão,1
1,Surto,Leptospirose nao especificada,1420070400000000000,201453,2015,Acre (AC),120040,1938,2001578,2014-12-26,...,0,1,1,2,Alta,1,12,52,Verão,1
2,Surto,Leptospirose nao especificada,1420070400000000000,201453,2015,Rio Grande do Sul (RS),431730,1593,2232715,2015-01-01,...,1,0,0,1,Moderada,0,1,1,Verão,1
3,Surto,Leptospirose nao especificada,1420070400000000000,201453,2015,Paraná (PR),412550,1356,2753278,2014-12-26,...,0,0,0,0,Baixa,0,12,52,Verão,1
4,Surto,Leptospirose nao especificada,1420070400000000000,201453,2015,São Paulo (SP),351300,1335,6212573,2014-12-29,...,0,0,0,0,Baixa,0,12,1,Verão,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27515,Surto,Leptospirose,1735603200000000000,202501,2024,Espírito Santo (ES),320120,Não informado,25478,2024-12-19,...,0,0,1,1,Moderada,0,12,51,Verão,1
27516,Surto,Leptospirose,1735603200000000000,202501,2024,Espírito Santo (ES),320010,Não informado,24028,2024-12-23,...,0,0,0,0,Baixa,0,12,52,Verão,1
27517,Surto,Leptospirose,1735603200000000000,202501,2024,Espírito Santo (ES),320010,Não informado,24028,2024-12-27,...,0,0,1,1,Moderada,0,12,52,Verão,1
27518,Surto,Leptospirose,1735257600000000000,202452,2024,Espírito Santo (ES),320520,Não informado,25469,2024-12-24,...,0,1,0,1,Moderada,0,12,52,Verão,1
27519,Surto,Leptospirose,1733875200000000000,202450,2024,Espírito Santo (ES),320120,Não informado,25481,2024-12-04,...,0,0,0,0,Baixa,0,12,49,Verão,1

In [15]:
df_atlas['id_municipio'] = df_atlas['id_municipio']//10
df_atlas_recent=df_atlas.groupby('id_municipio').tail(1)

In [16]:
df_merge=pd.merge(df_train,df_atlas_recent,on=['id_municipio'],how='inner')

In [18]:
df_merge

,tp_not,id_agravo,dt_notific,sem_not,nu_ano,sg_uf_not,id_municipio,id_regiona,id_unidade,dt_sin_pri,sem_pri,ano_nasc,nu_idade_n,cs_sexo,cs_gestant,cs_raca,cs_escol_n,sg_uf,id_mn_resi,id_rg_resi,id_pais,nduplic_n,dt_digita,dt_transus,dt_transdm,dt_transsm,dt_transrs,dt_transse,nu_lote_v,dt_invest,id_ocupa_n,ant_cb_lam,ant_cb_cri,ant_cb_cai,ant_cb_fos,ant_cb_sin,ant_cb_pla,ant_cb_cor,ant_cb_roe,ant_cb_gra,ant_cb_ter,ant_cb_lix,ant_cb_out,ant_ou_des,ant_humano,ant_animai,cli_dt_ate,cli_febre,cli_mialgi,cli_cefale,cli_prost,cli_conges,cli_pantur,cli_vomito,cli_diarre,cli_icteri,cli_renal,cli_respir,cli_cardia,cli_hemopu,cli_hemorr,cli_mening,cli_outros,cli_otrdes,ate_hosp,ate_dt_int,ate_dt_alt,ate_uf,ate_munici,lab_dt_1,lab_elis_1,lab_dt_2,lab_elis_2,dtmicro1,micro1_s1,micro1_t_1,micro1_s_2,micro1_t_2,lab_micr_1,dtmicro2,micro2_s1,micro2_t_1,micro2_s_2,micro2_t_2,lab_micr_2,dtisola,res_isol,dtimuno,res_imuno,dt_pcr,res_pcr,classi_fin,criterio,tpautocto,coufinf,copaisinf,comuninf,con_area,con_ambien,doenca_tra,evolucao,dt_obito,dt_encerra,dt_risco1,dt_risco2,co_mun_r1,co_mun_r2,co_mun_r3,co_mun_r4,co_uf_r1,co_uf_r2,co_uf_r3,co_uf_r4,ano,idade_anos,faixa_etaria,classi_fin_valido,evolucao_valido,baixa_escolaridade,raca_vulneravel,faixa_vulneravel,vulnerabilidade_social,nivel_vulnerabilidade,alta_vulnerabilidade,mes_sintomas,semana_sintomas,estacao,periodo_chuvoso,expectativa_vida,fecundidade_total,prob_sobrevivencia_40,prob_sobrevivencia_60,taxa_freq_bruta_basico,taxa_freq_bruta_fundamental,taxa_freq_bruta_medio,taxa_freq_liquida_superior,prop_pobreza_extrema,prop_vulner_pobreza,taxa_agua_encanada,taxa_banheiro_agua_encanada,taxa_coleta_lixo,taxa_energia_eletrica,taxa_agua_esgoto_inadequados,taxa_paredes_inadequados,populacao,indice_escolaridade,indice_frequencia_escolar,idhm,idhm_e,idhm_l,idhm_r
0,Surto,Leptospirose nao especificada,1420070400000000000,201453,2015,Minas Gerais (MG),317020,1462,5617286,2014-12-28,201453,2003,11.0,Masculino,Não se aplica,Não informado,Não informado,MG,317020,1462,1,Não informado,20150102,Não informado,Não informado,20150108,Não informado,Não informado,0000000,20150101,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Sim,Sim,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,20150101,Sim,Sim,Sim,Não,Não,Não,Não,Não,Não,Não,Sim,Não,Não,Não,Não,Não,Não informado,Sim,20150101,Não informado,MG,317020,20150102,Não reagente,Não informado,Não Realizado,Não informado,Não informado,Não informado,Não informado,Não informado,Inconclusivo,Não informado,Não informado,Não informado,Não informado,Não informado,Inconclusivo,Não informado,Não Realizado,Não informado,Não Realizado,Não informado,Não Realizado,Descartado,Laboratorial,Não informado,Não informado,0,Não informado,Não informado,Não informado,Não informado,Cura,Não informado,20150120,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,2015,11.0,1-12 anos,NaN,Cura,0,0,1,1,Moderada,0,12,52,Verão,1,78.09,1.7,95.28,86.69,101.77,110.28,79.42,25.24,0.70,12.41,99.52,98.97,99.85,99.92,0.18,0.5,604013,0.646,0.754,0.789,0.716,0.885,0.776
1,Surto,Leptospirose nao especificada,1421020800000000000,201502,2015,Minas Gerais (MG),317020,1462,2152924,2014-12-15,201451,1996,18.0,Masculino,Não se aplica,Branca,Não informado,MG,317020,1462,1,Não informado,20150113,Não informado,Não informado,20150205,Não informado,Não informado,0000000,20150112,Não informado,Não,Sim,Não,Não,Sim,Não,Não,Não,Não,Não,Não,Não,Não informado,Não informado,Não informado,20141215,Sim,Sim,Sim,Não,Não,Não,Sim,Sim,Não,Não,Sim,Não,Sim,Sim,Não,Sim,DOR ABDOMINAL,Sim,20141222,Não informado,MG,317020,20141222,Reagente,Não informado,Não Realizado,20141222,1 - ANDAMANA,100,26 - SHERMANI,100,Reagente,Não informado,Não informado,Não informado,Não informado,Não informado,Inconclusivo,Não informado,Não Realizado,Não informado,Não Realizado,Não informado,Não Realizado,Confirmado,Laboratorial,Não informado,MG,1,317020,Rural,Domicílio,Não,Óbito por leptospirose,20141222,20150113,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,2015,18.0,13-18 anos,NaN,Óbito por leptospirose,0,0,0,0,Baixa,0,12,51,Verão,1,78.09,1.7,95.28,86.69,101.77,110.28,79.42,25.24,0.70,12.41,99.52,98.97,99.85,99.92,0.18,0.5,604013,0.646,0.754,0.789,0.716,0.885,0.776
2,Surto,Leptospirose nao especificada,1421452800000000000,201502,2015,Minas Gerais (MG),317020,1462,2151871,2015-01-11,201502,1976,39.0,Masculino,Não se aplica,Não informado,Não informado,MG,313420,1378,1,Não informado,20150319,Não informado,Não informado,Não informado,Não informado,Não informado,0000000,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,0,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,2015,39.0,31-50 anos,NaN,None,0,0,0,0,Baixa,0,1,2,Verão,1,78.09,1.7,95.28,86.69,101.77,110.28,79.42,25.24,0.70,12.41,99.52,98.97,99.85,99.92,0.18,0.5,604013,0.646,0.754,0.789,0.716,0.885,0.776
3,Surto,Leptospirose nao especificada,1422921600000000000,201505,2015,Minas Gerais (MG),317020,1462,2152959,2014-12-02,201449,1980,34.0,Masculino,Não se aplica,Não informado,Não informado,MG,317020,1462,1,Não informado,20150205,Não informado,Não informado,20150205,Não informado,Não informado,0000000,20150203,Não informado,Não,Não,Não,Não,Não,Não,Sim,Não,Não,Não,Não,Não,Não informado,Não informado,Não informado,20150128,Não,Sim,Sim,Sim,Não,Não,Não,Não,Sim,Não,Não,Não,Não,Não,Não,Sim,COLURIA,Sim,20150128,Não informado,MG,317020,20150204,Não reagente,Não informado,Não Realizado,Não informado,Não informado,Não informado,Não informado,Não informado,Inconclusivo,Não informado,Não informado,Não informado,Não informado,Não informado,Inconclusivo,Não informado,Não Realizado,Não informado,Não Realizado,Não informado,Não Realizado,Descartado,Laboratorial,Não informado,Não informado,0,Não informado,Não informado,Não informado,Não informado,Cura,Não informado,20150219,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,2015,34.0,31-50 anos,NaN,Cura,0,0,0,0,Baixa,0,12,49,Verão,1,78.09,1.7,95.28,86.69,101.77,110.28,79.42,25.24,0.70,12.41,99.52,98.97,99.85,99.92,0.18,0.5,604013,0.646,0.754,0.789,0.716,0.885,0.776
4,Surto,Leptospirose nao especificada,1423440000000000000,201506,2015,Minas Gerais (MG),317020,1462,2146355,2015-01-28,201504,1957,57.0,Feminino,Não se aplica,Branca,Não informado,MG,310375,1462,1,Não informado,20150209,Não informado,Não informado,20151127,Não informado,Não informado,0000000,20150209,Não informado,Não,Não,Não,Não,Sim,Não,Não,Não,Não,Sim,Sim,Não,Não informado,Não,Não,20150207,Sim,Sim,Sim,Sim,Sim,Sim,Não,Não,Sim,Sim,Sim,Não,Sim,Sim,Não,Não,Não informado,Sim,20150207,Não informado,MG,317020,20150209,Não reagente,Não informado,Não Realizado,Não informado,Não informado,Não informado,Não informado,Não informado,Inconclusivo,Não informado,Não informado,Não informado,Não informado,Não informado,Inconclusivo,Não informado,Não Realizado,Não informado,Não Realizado,Não informado,Não Realizado,Descartado,Laboratorial,Não informado,Não informado,0,Não informado,Não informado,Não informado,Não informado,Cura,Não informado,20150224,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,2015,57.0,51-65 anos,NaN,Cura,0,0,0,0,Baixa,0,1,5,Verão,1,78.09,1.7,95.28,86.69,101.77,110.28,79.42,25.24,0.70,12.41,99.52,98.97,99.85,99.92,0.18,0.5,604013,0.646,0.754,0.789,0.716,0.885,0.776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169921,Surto,Leptospirose,1715644800000000000,202420,2024,Espírito Santo (ES),320110,Não informado,75216,2024-05-02,202418,1983,40.0,Masculino,Não se aplica,Branca,Ensino médio completo,ES,320110,Não informado,BRAS,0,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Sim,Sim,Não informado,Sim,Sim,Não informado,Sim,Sim,Não informado,Sim,Sim,Não informado,Não informado,Não informado,Não informado,Não informado,Sim,Sim,Sim,Não informado,Não informado,Sim,Sim,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Descartado,Não informado,Sim,Não informado,1,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,20240617,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,2024,40.0,31-50 anos,NaN,None,0,0,0,0,Baixa,0,5,18,Outono,0,76.22,1.9,93.32,83.90,102.70,110.18,82.38,14.37,1.54,33.86,97.95,99.63,99.64,98.97,0.24,0.2,9476,0.567,0.733,0.734,0.673,0.854,0.689
169922,Surto,Leptospirose,1715644800000000000,202420,2024,Espírito Santo (ES),320110,Não informado,31709,2024-05-07,202419,2012,12.0,Masculino,Não se aplica,Amarela,5ª a 8ª série incompleta do EF,ES,320110,Não informado,BRAS,0,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,20240514,100.01,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Descartado,Não informado,Sim,Não informado,1,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,20240617,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,2024,12.0,1-12 anos,NaN,None,1,0,1,2,Alta,1,5,19,Outono,0,76.22,1.9,93.32,83.90,102.70,110.18,82.38,14.37,1.54,33.86,97.95,99.63,99.64,98.97,0.24,0.2,9476,0.567,0.733,0.734,0.673,0.854,0.689
169923,Surto,Leptospirose,1716336000000000000,202421,2024,Espírito Santo (ES),320110,Não informado,31709,2024-05-17,202420,2012,12.0,Masculino,Não se aplica,Preta,Ensino fundamental completo,ES,320110,Não informado,BRAS,0,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,20240522,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Sim,Sim,Sim,Não informado,Não informado,Sim,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Descartado,Não informado,Sim,Não informado,1,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,20240617,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,2024,12.0,1-12 anos,NaN,None,0,1,1,2,Alta,1,5,20,Outono,0,76.22,1.9,93.32,83.90,102.70,110.18,82.38,14.37,1.54,33.86,97.95,99.63,99.64,98.97,0.24,0.2,9476,0.567,0.733,0.734,0.673,0.854,0.689
169924,Surto,Leptospirose,1717632000000000000,202423,2024,Espírito Santo (ES),320110,Não informado,24467,2024-06-03,202423,1989,35.0,Masculino,Não se aplica,Preta,Ensino médio completo,ES,320110,Não informado,BRAS,0,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,20240606,Não informado,Sim,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Sim,Não informado,Não informado,Sim,Não informado,20240606,Sim,Sim,Sim,Sim,Não informado,Não informado,Não informado,Sim,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Sim,dor em mmii,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não Realizado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Descartado,Não informado,Sim,Não informado,1,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,20240815,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,2024,35.0,31-50 anos,NaN,None,0,1,0,1,Moderada,0,6,23,Inverno,0,76.22,1.9,93.32,83.90,102.70,110.18,82.38,14.37,1.54,33.86,97.95,99.63,99.64,98.97,0.24,0.2,9476,0.567,0.733,0.734,0.673,0.854,0.689
169925,Surto,Leptospirose,1727395200000000000,202439,2024,Espírito Santo (ES),320110,Não informado,31709,2024-09-25,202439,2001,23.0,Masculino,Não se aplica,Branca,Ensino médio completo,ES,320110,Não informado,BRAS,0,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não,Não,Não,Não,Não,Não,Não,Não,Não,Não informado,Não informado,Não,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Sim,Não informado,Não informado,Não informado,Sim,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Sim,Não informado,1,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,Não informado,2024,23.0,19-30 anos,NaN,None,0,0,0,0,Baixa,0,9,39,Primavera,0,76.22,1.9,93.32,83.90,102.70,110.18,82.38,14.37,1.54,33.86,97.95,99.63,99.64,98.97,0.24,0.2,9476,0.567,0.733,0.734,0.673,0.854,0.689

### Merge dados Ocupação Ministério do Trabalho

In [19]:
# Baixe ou clone o repositório datasets-br/cbo e carregue o arquivo
url = "https://raw.githubusercontent.com/datasets-br/cbo/master/data/lista.csv"
cbo = pd.read_csv(url, dtype={"codigo": str})
cbo['codigo'] = cbo['codigo'].apply(lambda x: x.replace('-',''))
#cbo['codigo'] = pd.to_numeric(cbo['codigo'],errors='coerce') 
# Criar dicionário código → termo
mapa_cbo = dict(zip(cbo["codigo"], cbo["termo"]))

def mapear_ocupacao(df, coluna="id_ocupa_n"):
    df = df.copy()
    df[coluna] = df[coluna].map(mapa_cbo)
    df[coluna] =df[coluna].fillna('Nao informado')
    return df

In [20]:
df_merge=mapear_ocupacao(df_merge, coluna="id_ocupa_n")

In [26]:
df_merge

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169926 entries, 0 to 169925
Columns: 151 entries, tp_not to idhm_r
dtypes: UInt32(1), category(2), datetime64[ns](1), float64(25), int32(8), int64(4), object(110)
memory usage: 187.8+ MB

Save file

In [27]:
df_merge.to_parquet('processed/df_lept_atlas_ocup.parquet')

In [36]:
df_merge.to_csv('processed/df_lept_atlas_ocup.csv',index=False)

In [38]:
cbo.to_csv('raw/lista_cbo.csv')